# Generated by Django 3.1 on 2020-08-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_per_trial', models.IntegerField()),
                ('num_trials', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('organization', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(blank=True, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('did_timeout', models.BooleanField(default=False)),
                ('input_sequence', models.CharField(max_length=50)),
                ('time', models.FloatField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestureApp.block')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestureApp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('code', models.CharField(blank=True, editable=False, max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('num_blocks', models.IntegerField(default=1)),
                ('resting_time', models.IntegerField(default=10)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestureApp.designer')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='gestureApp.experiment'),
        ),
        migrations.AddField(
            model_name='block',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestureApp.sequence'),
        ),
    ]
