# Generated by Django 3.1 on 2020-08-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='time',
            field=models.FloatField(null=True),
        ),
    ]
