# Generated by Django 3.1.3 on 2020-11-10 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='time_per_trial',
            new_name='max_time_per_trial',
        ),
        migrations.AddField(
            model_name='block',
            name='max_time',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('max_time', 'Max Time'), ('num_trials', 'Num Trials')], default=5, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='num_trials',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='gestureApp.user'),
            preserve_default=False,
        ),
    ]
