# Generated by Django 3.1.3 on 2020-11-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0002_auto_20201110_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='correct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
