# Generated by Django 3.1.3 on 2021-01-21 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0003_trial_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='num_practice_trials',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='trial',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='gestureApp.block'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trials', to='gestureApp.subject'),
        ),
    ]
