# Generated by Django 3.1.3 on 2021-02-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0004_auto_20210121_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='sec_until_next',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experiment',
            name='practice_is_random_seq',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='practice_seq',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='experiment',
            name='with_practice_trials',
            field=models.BooleanField(default=True),
        ),
    ]
