# Generated by Django 3.1.3 on 2021-02-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0005_auto_20210203_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='num_practice_trials',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='practice_is_random_seq',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='practice_seq',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
