# Generated by Django 3.1.3 on 2021-02-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0006_auto_20210203_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='is_random',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='seq_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='max_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='max_time_per_trial',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='block',
            name='resting_time',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='block',
            name='sec_until_next',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='block',
            name='sequence',
            field=models.CharField(max_length=50),
        ),
    ]
