# Generated by Django 3.1.3 on 2021-02-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0007_auto_20210219_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='is_fixed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='practice_seq_length',
            field=models.IntegerField(null=True),
        ),
    ]
