# Generated by Django 3.1.3 on 2021-02-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0008_auto_20210219_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='practice_seq_length',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
