# Generated by Django 3.1.3 on 2021-02-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0009_auto_20210219_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='practice_rest_time',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='experiment',
            name='practice_trial_time',
            field=models.FloatField(default=5),
        ),
    ]
