# Generated by Django 3.1.3 on 2021-02-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0010_auto_20210219_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keypress',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='experiment',
            name='practice_rest_time',
            field=models.FloatField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='practice_trial_time',
            field=models.FloatField(default=5, null=True),
        ),
    ]
