# Generated by Django 3.1.3 on 2021-03-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0013_experiment_published_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='published_timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
