# Generated by Django 3.1.3 on 2021-04-20 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0014_auto_20210325_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='age',
        ),
        migrations.CreateModel(
            name='EndSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('comments', models.TextField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestureApp.experiment')),
                ('subject', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey', to='gestureApp.subject')),
            ],
        ),
    ]
