# Generated by Django 3.1.3 on 2021-04-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0015_auto_20210420_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endsurvey',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
