# Generated by Django 3.1.3 on 2021-04-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0016_auto_20210422_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='num_practice_trials',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='practice_is_random_seq',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='practice_rest_time',
            field=models.FloatField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='practice_seq',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='practice_seq_length',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='practice_trial_time',
            field=models.FloatField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='published_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
