# Generated by Django 3.1.3 on 2021-04-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0017_auto_20210422_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='endsurvey',
            name='comp_type',
            field=models.CharField(default='laptop', max_length=35),
            preserve_default=False,
        ),
    ]
