# Generated by Django 3.1.3 on 2021-04-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0020_experiment_with_feedback_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='timezone_offset',
            field=models.CharField(default='GMT-04:00', max_length=15),
        ),
    ]
