# Generated by Django 3.1.3 on 2021-05-05 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0023_trial_partial_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='finished_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 13, 5, 30, 501556, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
