# Generated by Django 3.1.3 on 2021-05-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0024_trial_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='endsurvey',
            name='excercise_regularly',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endsurvey',
            name='followed_instructions',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endsurvey',
            name='hours_of_sleep',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endsurvey',
            name='keypress_experiment_before',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endsurvey',
            name='medical_condition',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
