# Generated by Django 3.1.3 on 2021-05-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0027_experiment_rest_after_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='endsurvey',
            name='dominant_hand',
            field=models.CharField(default='right', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endsurvey',
            name='level_education',
            field=models.CharField(default="master's or doctoral degree", max_length=30),
            preserve_default=False,
        ),
    ]
