# Generated by Django 3.1.3 on 2021-05-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0028_auto_20210524_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endsurvey',
            name='level_education',
            field=models.CharField(max_length=50),
        ),
    ]
