# Generated by Django 3.1.3 on 2021-06-03 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0030_experiment_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('code', models.CharField(blank=True, editable=False, max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('published_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='gestureApp.study'),
        ),
    ]
