# Generated by Django 3.1.3 on 2021-06-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0031_auto_20210603_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
