# Generated by Django 3.1.3 on 2021-06-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0033_auto_20210608_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
