# Generated by Django 4.0.4 on 2025-02-25 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestureApp', '0038_experiment_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endsurvey',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='gestureApp.subject'),
        ),
    ]
